### ISSUE TITLE
Restito 1.1.0 not working with CXF 4.0.4

### ISSUE THREAD

**Issue by subijayb** [mkotsur/restito#89] opened 2024-05-08 12:41 UTC
Hi,

We have been using [Webclient](https://cxf.apache.org/javadoc/latest-3.5.x/org/apache/cxf/jaxrs/client/WebClient.html)#invoke() to invoke any endpoint. CXF version used was 3.5.5. For unit testing purpose we used restito 0.9.5 with JDK 11 and it worked fine.

Now, we are have upgraded to CXF 4.0.4, restito 1.1.0 with JDK 17. W

While our code gets deployed on Wildfly server and is able to invoke rest endpoints, the unit test cases are failing after the upgrades. We get below error (Also attached the logs)
Problem reading Post Body of HTTP call
     1: com.xebialabs.restito.semantics.Call.fromRequest(Call.java:54)
     2: com.xebialabs.restito.server.StubServer$1.service(StubServer.java:255)
     3: org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
     4: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
     5: org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
     6: java.base/java.lang.Thread.run(Thread.java:842)

We downgraded CXF to 3.5.5 with restito 1.1.0 and JDK 17, it worked again. So, I have a feeling restito is not working with CXF 4.0.4. But as mentioned earlier, we dont think there is any problem in CXF 4.x code and in real time deployments we get responses.

Is there any way we can find the root cause why restito server is throwing 500 Internal server error? Maybe enable restito logs/print statements?
[restitio-cxf-error.txt](https://github.com/mkotsur/restito/files/15248962/restitio-cxf-error.txt)

**Comment by mkotsur** [comment] 2024-05-12 18:13
Hi @subijayb. This is strange, I don't have an idea why is that, but I've released the version 1.1.1 with some improvement with regard to exception handling. This should show what exactly is the reason why Resito can't handle the POST request. Could you try to run the tests with CXF 4.0.4 and Restito 1.1.1 and show me the logs?

**Comment by subijayb** [comment] 2024-05-13 04:47
Hi @mkotsur . Thanks for checking this. I could not find the release version 1.1.1 in either [maven repo](https://mvnrepository.com/artifact/com.xebialabs.restito/restito) or under the [tag](https://github.com/mkotsur/restito/tags). 
Am I missing something?

**Comment by mkotsur** [comment] 2024-05-13 10:26
The search doesn't find it yet probably due to indexing lag, but the artifact is there: https://repo.maven.apache.org/maven2/com/xebialabs/restito/restito/1.1.1/

If you update the dependency version in your build file, it should work!

**Comment by subijayb** [comment] 2024-05-13 11:49
Hi @mkotsur , I ran with restitio 1.1.1. I am attaching the logs 
[restito-cxf4-root-cause.txt](https://github.com/mkotsur/restito/files/15293891/restito-cxf4-root-cause.txt)

Also, please note, this is happening for GET, PUT, and other http methods as well

**Comment by mkotsur** [comment] 2024-05-13 17:19
Hi @subijayb , I think I managed to reproduce the issue on a minimal setup with CXF 4. Hopefully it's fixed in 1.1.2. Could you pls check?

https://repo.maven.apache.org/maven2/com/xebialabs/restito/restito/1.1.2/

**Comment by subijayb** [comment] 2024-05-14 04:13
Thanks a lot @mkotsur . version 1.1.2 worked like a charm.

**Closed** 2024-05-14 04:13 UTC
